#ifndef FRAME_PROCESSOR_H
#define FRAME_PROCESSOR_H

/* Some cross-platform definitions generated by autotools */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */

#endif /* FRAME_PROCESSOR_H */
